import './globals.css';
import {
  Roboto_Flex as RobotoFlex,
  Bai_Jamjuree as BaiJamjuree
} from 'next/font/google';

const robotoFlex = RobotoFlex({
  subsets: ['latin'],
  variable: '--font-roboto'
});
const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        suppressHydrationWarning={true}
        className={`${robotoFlex.variable} ${baiJamjuree.variable} flex h-screen justify-center bg-blue-800 font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
